---
- hosts: all
  become: true
  tasks:
    - name: Stop and Remove Existing Containers
      community.docker.docker_compose:
        project_src: /ibobots/modmail
        state: absent

    - name: Pull Latest Docker Image
      community.docker.docker_compose:
        project_src: /ibobots/modmail
        pull: true

    - name: Deploy Docker Image
      community.docker.docker_compose:
        project_src: /ibobots/modmail
        build: false
