[project]
name = "modmail.py"
version = "2.0.2"
readme = "README.md"
description = "A Discord bot for managing modmail written in Python."

[tool.pyright]
venvPath = "."
venv = "venv"

[tool.ruff]
line-length = 95
